version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
    labels: ["deps", "github-actions"]
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "weekly" }
    labels: ["deps", "security"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule: { interval: "weekly" }
    labels: ["deps", "security"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule: { interval: "weekly" }
    labels: ["deps", "security"]
